[package]
name = "kat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.12"
regex = "1.6.0"
csv = "1.1.6"

[dev-dependencies]
rand = "0.8.5"
assert_cmd = "2.0.4"
predicates = "2.1.1"